# Generated by Django 3.0.4 on 2020-05-05 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlatListingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=14, region=None)),
                ('location', models.CharField(max_length=100)),
                ('longitude', models.FloatField(blank=True, default=0.0)),
                ('latitude', models.FloatField(blank=True, default=0.0)),
                ('flat_description', models.CharField(max_length=2000)),
                ('flat_size', models.PositiveIntegerField(default=0)),
                ('total_rent', models.PositiveIntegerField(default=0)),
                ('post_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('photos', models.ImageField(blank=True, upload_to='images/flats')),
                ('userprofileinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tolet.UserProfileInfo')),
            ],
        ),
    ]
