# Generated by Django 3.0.4 on 2020-05-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tolet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatlistinginfo',
            name='photos',
            field=models.ImageField(blank=True, upload_to='media/images/flats'),
        ),
    ]
