# Generated by Django 3.0.4 on 2020-05-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tolet', '0002_auto_20200505_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatlistinginfo',
            name='photos',
            field=models.ImageField(blank=True, upload_to='images/flats'),
        ),
    ]
